### PR TITLE
seL4sharedDataWithCaps: Add frame size getter

### PR DESCRIPTION
**Pull request by hlyytine**
This allows other code to map dataport frames with correct page size.

### CODE REVIEW

**Comment by kent-mcleod** [comment]
> I'm wondering whether it needs to be commented that it is OK to use the size of the first frame, since CAmkES tooling uses the same frame size for all.

Maybe on line 46 in this file, and a comment on the implementation of get_page_size in macros.py in camkes_tool.git that this function should never be changed to allow different page sizes for a region.

**Comment by hlyytine** [comment]
I worded it a bit differently -- telling why is it OK to do it like this here. I wouldn't want to present when anybody changes the semantics of `register_shared_variable()` -- breaking `seL4SharedDataWithCaps` would be one the smallest worries.

Also spotted and fixed one theoretical integer overflow.

**Review by axel-h — APPROVED** [review]
Looks good to me.

**Comment by hlyytine** [comment]
Just wondering aloud -- shall we use the term `page` or `frame` here? I find the lack of consistency disturbing.

**Comment by axel-h** [comment]
> Just wondering aloud -- shall we use the term `page` or `frame` here? I find the lack of consistency disturbing.

I was wondering also, but "page" is correct, as the usual definition is, that a frame is made of pages, wher

**Comment by gernotheiser** [comment]
Standard usage is that "page" refers to virtual memory, "frame" to physical memory. I tried to get this cleaned up years ago but there wasn't much enthusiasm in consistentcy

**Comment by hlyytine** [comment]
I came to conclusion we should use `get_frame_size_bits()` instead:

- CAmkES tooling selects as large as possible page size supported by MMU and creates frames of this size -- yes, frame size is selected based on best page size, but still it is what it is
- Dataport code (in `camkes-tool` and `global-components`) does not deal with mapping into vspace at all -- hence there is little reason to use `page` there
- `sel4_projects_libs` code or the iterator function thereof returns `vm_frame_t`, which contains the size bits.

Only inside `vm_map_reservation()` we equate frame size and page size, but up until that point, page size does not make that much sense.

Changed the PRs accordingly (and squashed the `size` redundant field removal into single commit here as well).

**Review by kent-mcleod — APPROVED** [review]

**Pull request merged**
