### PR TITLE
Provide a convenience function to wait for a notification.

### PR DESCRIPTION
**Pull request by axel-h**
Provide a convenience function to wait for a notification and don't bother the caller with all the details.

### CODE REVIEW

**Review by kent-mcleod — APPROVED** [review]

**Comment by xurtis** [comment]
@ssrg-bamboo `test`

**Comment by ssrg-bamboo** [comment]
Hello, I'm a bot! I'll bring this PR into Trustworthy Systems and run some tests

**Comment by axel-h** [comment]
is bamboo stuck?

**Comment by xurtis** [comment]
@ssrg-bamboo `test`

**Comment by ssrg-bamboo** [comment]
Hello, I'm a bot! I'll bring this PR into Trustworthy Systems and run some tests

**Pull request merged**
