### PR TITLE
fix: patches from kent

### PR DESCRIPTION
**Pull request by ridale**
Patches to fix libethdrivers so they work with Axel-H's changes to the ethdriver system, there is also a patch in util_libs

### CODE REVIEW

**Comment by axel-h** [comment]
please rewrite the commit comment:
* seem this is basically mapping the DMA buffer uncached now?
* Signed-off-by should be a valid email address

**Comment by wom-bat** [comment]
You only need to map the buffer uncached if DMA is not coherent with CPU traffic.  I.e., on armv7 and some (most?) aarch64.  It can be mapped cached for x86, and any other platform that has a PIPT cache.  I don't know enough about RISC-V to say if it's needed here.

What I think's needed is a #define that says whether DMA and CPU are cache-coherent, and use that here.

**Comment by kent-mcleod** [comment]
> What I think's needed is a #define that says whether DMA and CPU are cache-coherent, and use that here.

I'm going to try checking the return code of ps_dma_alloc() after a cached request and if it failed, fall back to an uncached request.  The assumption is that the CAmkES configuration will have only defined DMA pools with the right cache attribute for the platform.

**Comment by ridale** [comment]
@kent-mcleod If you are prepared to take this over I am happy to close this MR.

It might be handy to leave open for anyone trying to get the ethernet camkes components to work on the aarch64 platforms until a MR with the correct solution is available.

**Comment by kent-mcleod** [comment]
> @kent-mcleod If you are prepared to take this over I am happy to close this MR.
> 
> It might be handy to leave open for anyone trying to get the ethernet camkes components to work on the aarch64 platforms until a MR with the correct solution is available.

This is still a bit hacky, but it would at least still allow x86 platforms to continue to use cached dma mappings: https://github.com/seL4/global-components/pull/46

**Comment by ridale** [comment]
Closing this in favor of MR #46

**Pull request closed without merging**
